### ISSUE TITLE
Add italics

### ISSUE THREAD

**Issue by cssobral2013** [MattBaileyDesign/Spartan-MB#1]

**Comment by cssobral2013** [comment]
@MattBaileyDesign - I just opened a PR for this on #7.

**Comment by MattBaileyDesign** [comment]
Thanks for this, super useful addition. Not sure if it's issues on my end, but in the source files (VFC), some weights flip the parenthesis the wrong way (need to be flipped again vertically). I haven't really looked at the rest of the file, yet, but I'm super excited that this has been added. Really appreciate your work!

**Comment by cssobral2013** [comment]
@MattBaileyDesign - Thank ya for accepting! As such, this issue will be closed now.

**Comment by cssobral2013** [comment]
@MattBaileyDesign - This Issue is also displayed on statics, but only in Medium Italic and ExtraBold Italic.

**Comment by MattBaileyDesign** [comment]
Gotcha. As it stands, I don't see myself being able to get to this in the near future, but I'm sure we'll iron these issues out at some point!

**Comment by cssobral2013** [comment]
@MattBaileyDesign - I already fixed this. See #8, and please accept it.
